### ISSUE TITLE
Publish a binary

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/mbview#1]
@rodowi - It would be great if anyone could `npm install mbview -g` and have it just work from there.

For example, see how togeojson does it: https://github.com/mapbox/togeojson

**Comment by rodowi** [comment]
```bash
➜  ~ node --version
v0.10.43
➜  ~ npm install -g mbview
...
➜  ~ mbview
usage: node cli.js [options]

 --mbtiles path to mbtiles file
 --port sets port to use
 --help prints this message
```
