### ISSUE TITLE
NPM install failing

### ISSUE THREAD

**Issue by nonoumasy** [mapbox/mbview#101]
$ npm -v
6.14.4
$ node -v
v12.16.3

npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/mbview/cli.js
npm ERR! dest /usr/local/bin/mbview
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/mbview/cli.js' -> '/usr/local/bin/mbview'
npm ERR! File exists: /usr/local/bin/mbview
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
$ mbview
-bash: mbview: command not found

**Comment by mattficke** [comment]
@nonoumasy there might be a conflict if you have an earlier installation of `mbview` from before we switched to the `@mapbox` namespace. Can you try uninstalling the existing package with `npm uninstall -g mbview` and reinstalling with `npm install -g @mapbox/mbview`?
