### ISSUE TITLE
Find the difference between 2 mbtiles

### ISSUE THREAD

**Issue by Nerdyvedi** [mapbox/mbview#104]
Hi,
How can I use mbview to visulaise the difference between 2 mbtiles file.  For instance, I want to find the roads that are present in 1st file, and not in the second. 
Is it possible to do something like this using mbview ?

**Comment by mattficke** [comment]
Hi @Nerdyvedi, mbview probably isn't going to be the right tool for that. You could do whatever filtering you need at the data level before creating tiles, then create a tileset with just that data, which you could inspect with mbview.

You could also look into uploading both mbtiles files to Mapbox Studio and creating a custom style with the tilesets layered on top of each other in different colors to see where they don't overlap: https://docs.mapbox.com/studio-manual/overview/
