### ISSUE TITLE
Undefined color

### ISSUE THREAD

**Issue by rodowi** [mapbox/mbview#24]
Sometimes randomColor returns undefined (perhaps out of bounds?)

https://github.com/mapbox/mbview/blob/420160ffd50a9c4ad5652af78da14b6a59588bd3/views/map.ejs#L43

<img width="569" alt="screen shot 2016-05-07 at 11 55 06 pm" src="https://cloud.githubusercontent.com/assets/705860/15096503/1f72710a-14b0-11e6-967f-4c30fee02367.png">

**Comment by rodowi** [comment]
```javascript
var randomNumber = parseInt(Math.random() * colors.length + 1);
```

We should remove that last addition.

Math.random() returns a value between 0...1 which means that we will never reach colors.length, that is [0.. colors.length - 1]. This is within the boundaries of the colors array.


As a reference see chroma.random()
https://github.com/gka/chroma.js/blob/f1b7ca5cc4156f7d766e45e13ed6496c7b8ff7da/chroma.js#L778

**Comment by aaronlidman** [comment]
Oh my bad
