### ISSUE TITLE
Add super dense mbtiles screenshot

### ISSUE THREAD

**Issue by rodowi** [mapbox/mbview#25]

**Comment by rodowi** [comment]
![awesome](https://cloud.githubusercontent.com/assets/58878/15119814/911a7754-15c7-11e6-9df3-b8546f570939.png)

**Comment by aaronlidman** [comment]
<img width="1452" alt="screen shot 2016-05-09 at 9 25 15 am" src="https://cloud.githubusercontent.com/assets/58878/15119908/fc49b9b8-15c7-11e6-99b8-8a590df46c37.png">

<img width="1644" alt="screen shot 2016-05-05 at 6 46 19 pm" src="https://cloud.githubusercontent.com/assets/58878/15119925/0a974634-15c8-11e6-852b-a7d411cd407f.png">

**Comment by rodowi** [comment]
Awesome
Added screenshots in #26
