### ISSUE TITLE
Spotted some unrendered features

### ISSUE THREAD

**Issue by rodowi** [mapbox/mbview#35]
You can see some roads on the mapbox streets layer but not on blue

<img width="632" alt="screen shot 2016-05-15 at 9 38 07 pm" src="https://cloud.githubusercontent.com/assets/705860/15280473/924eafdc-1ae5-11e6-847b-243398320d38.png">

**Comment by aaronlidman** [comment]
I believe that tile failed to load. See how it cuts along a straight line on the top and side?

**Comment by rodowi** [comment]
The MBTiles file used in this ticket is a Mexico OSM QA extract.

Related: https://github.com/osmlab/osm-qa-tiles/issues/17
There are some reported glitches on OSM QA Tiles.

**Comment by rodowi** [comment]
Closing, as this seems to be related to the QA tiles
