### ISSUE TITLE
Change map style with a switcher

### ISSUE THREAD

**Issue by bkowshik** [mapbox/mbview#46]
It would be useful to have a switcher to switch to a `satellite` base map. [Example](https://www.mapbox.com/mapbox-gl-js/example/setstyle/). Currently, I could change the map style with the following in my browser's JavaScript console.

```
map.setStyle('mapbox://styles/mapbox/satellite-v9');
```

Note: After the layer switch, I don't see the mbtiles data anymore.

**Comment by rodowi** [comment]
Have you tried using the --basemap parameter?

![basemap](https://cloud.githubusercontent.com/assets/705860/16496476/0f93b82c-3ec0-11e6-9dc2-aa827b77d738.gif)

Also: we are planning to add a style menu on #39

**Comment by bkowshik** [comment]
Thank you @rodowi. That works!
