### ISSUE TITLE
Show properties

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/mbview#47]
![screen shot 2016-07-31 at 2 34 04 pm](https://cloud.githubusercontent.com/assets/58878/17279554/e2245192-572b-11e6-8bd7-bfc34e8bb727.png)

Ideally like Mapbox studio does on hover of individual geometries.

**Comment by BergWerkGIS** [comment]
Need this today, too.

My quick hack was to put this into `map.ejs`:

```js
map.on('click', function (e) {
    var features = map.queryRenderedFeatures(e.point, {layers: layers.pts.concat(layers.lines) });
    if (!features.length) {
        console.log('no features');
        return;
    }

    var msg = '';
    features.forEach(function(f){
        msg+=JSON.stringify(f.properties) + '<br>';
    });

    var popup = new mapboxgl.Popup()
        .setLngLat(map.unproject(e.point))
        .setHTML(msg)
        .addTo(map);
});
```

**Comment by rodowi** [comment]
we could use a mouse over bounding box (to have some buffer)
https://www.mapbox.com/mapbox-gl-js/example/using-box-queryrenderedfeatures/
