### ISSUE TITLE
invalid access token

### ISSUE THREAD

**Issue by snodnipper** [mapbox/mbview#53]
It would appear that the access token has expired.  Maybe a configurable parameter is the way forward.

https://github.com/mapbox/mbview/blob/97c715f3605869135e0ef9c1d4627462e8db1081/views/map.ejs#L23
![screen shot 2016-12-21 at 16 40 31](https://cloud.githubusercontent.com/assets/576719/21397634/7fc98ce2-c79c-11e6-8088-b3dc5c44cc2c.png)

**Comment by rodowi** [comment]
thanks for reporting this @snodnipper 

I agree, a config param should be added and fallback to an ENV var

**Comment by rodowi** [comment]
@snodnipper you mind testing that #54 works on your local setup?

**Comment by snodnipper** [comment]
works great on my setup.  Thanks!

**Comment by rodowi** [comment]
fixed published in 1.7.1 https://www.npmjs.com/package/mbview
