### ISSUE TITLE
Can't display more than one mbtiles

### ISSUE THREAD

**Issue by rmrice** [mapbox/mbview#59]
I'm trying to compare 2 mbtilesets and only the last one in my command renders.

```
node cli.js --port 4000 -n mbtiles1.mbtiles mbtiles2.mbtiles
```

Not sure if this is a bug or if I'm missing something in the above command.

**Comment by andrewharvey** [comment]
The issue is the `-n` wasn't marked as a boolean so mbtiles1.mbtiles was being pickup up as the value for -n and not a filename. Fixed in #61.
