### ISSUE TITLE
Rendering problems in Chrome//Ubuntu

### ISSUE THREAD

**Issue by rmrice** [mapbox/mbview#66]
I'm getting rendering weirdness using mbview in Chrome (Ubuntu 16):

![screenshot from 2017-03-09 08-55-34](https://cloud.githubusercontent.com/assets/17434033/23753172/672df17c-04a6-11e7-88af-2106b1818f57.png)
![screenshot from 2017-03-09 08-55-57](https://cloud.githubusercontent.com/assets/17434033/23753173/6865f8e6-04a6-11e7-822c-0248d9b47eb9.png)

Works just fine in Firefox on Ubuntu. Also works in Chrome on my Mac, so exclusively a Chrome on Ubuntu problem.

Getting this in console in both browsers, so not sure if this is the root of the problem:
```
Geometry exceeds allowed extent, reduce your vector tile buffer size
```

Also worth noting my browser supports WebGL.

**Comment by aaronlidman** [comment]
Interesting. How did you create the vector tiles?

**Comment by rodowi** [comment]
Chrome on Ubuntu works fine for me

![screenshot from 2017-03-23 21 45 02](https://cloud.githubusercontent.com/assets/705860/24281028/901210e2-1012-11e7-8f30-78e7acafcdac.png)


@rmrice could you try loading the mbtiles from the examples directory? i.e. `mbview examples/baja-highways.mbtiles`

**Comment by rmrice** [comment]
The example mbtiles behave the same way:

![screenshot from 2017-03-24 08-33-40](https://cloud.githubusercontent.com/assets/17434033/24294438/cf3ae71c-106c-11e7-9bbe-a49f87170b3e.png)

The basemap is pretty wonky too, so I don't think it's due to how I created mbtiles.
![screenshot from 2017-03-24 08-28-44](https://cloud.githubusercontent.com/assets/17434033/24294441/d10e4390-106c-11e7-9e3c-e29a1797e1e0.png)

I'm on chrome 57.0.2987.110 which (I think) is the latest stable version. I had a friend test this out on his ubuntu machine (running the baja-highways.mbtiles) and he got the same behavior.

This isn't a huge issue for me since I can use another browser, it's just annoying / weird / something to be aware of.

**Comment by aaronlidman** [comment]
@rmrice - Would you mind upgrading and trying again? `npm install -g mbview`

I just put out a version with upgraded gl-js which was quite old and had a similar bug that has since been solved.

**Comment by rmrice** [comment]
it works now! thanks for updating @aaronlidman :+1:
