### ISSUE TITLE
lint ejs

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mbview#97]
https://github.com/RyanZim/EJS-Lint can be used to lint ejs however since we're still using legacy include (which prevents us from upgrading to ejs 3 btw https://github.com/mde/ejs/blob/master/CHANGELOG.md), I'm not sure if we can use ejs-lint yet.

**Comment by mattficke** [comment]
Adding this in https://github.com/mapbox/mbview/pull/103

**Comment by mattficke** [comment]
Done (finally), available in v5.0.0
