### ISSUE TITLE
Why using an apikey for local use ?

### ISSUE THREAD

**Issue by clement-igonet** [mapbox/mbview#99]
If the usage is local, what is the purpose of using an api key ?
Is it mandatory for local use ?

**Comment by andrewharvey** [comment]
The background map is using Mapbox. That said, in my opinion if you don't pass an API key it should just use a blank background instead of refusing to load at all.

**Comment by clement-igonet** [comment]
OK, good point. So no upload of my local mbtiles.
And so, if I just need to see my mbtiles data, nothing else, I should not need to pass api key, right ?

**Comment by andrewharvey** [comment]
Well it might not start without the access token, you might need to change the code to use an empty background style if the access token is not provided.

**Comment by clement-igonet** [comment]
OK. nop access token.
Thx.
